sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 333
  redis:
    host: localhost
    port: 6379
    database: 0
# 微信
  wechat:
    appid: wxff28b542ad569d79
    secret: 7965f23b5e1ced70aa0b98eb04a30273
#文件上传
file:
  location: http://localhost:8080/
  path:
    img: D:\\Download\\file\\img\\

