sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 333
  redis:
    host: localhost
    port: 6379
    database: 0
#文件上传
file:
  location: http://localhost:8080/
  path:
    img: D:\\Download\\file\\img\\

